/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Lottery.LotteryManager;
import Lottery.Raffle;
import Lottery.RaffleType;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Fanny Brenes
 */
public class Busquedasorteos extends javax.swing.JFrame {

    /**
     * Creates new form Busquedasorteos
     */
    private Raffle raffle;

    public Raffle getRaffle() {
        return raffle;
    }

    public Busquedasorteos() {
        initComponents();
        refreshSearch();

        this.nameRa.addItem("Nombre de rifas");
        for (Raffle raffle : LotteryManager.getInstance().getRaffles()) {
            nameRa.addItem(raffle.getName());
        }

        this.typeRa.addItem("Tipos");
        for (RaffleType topic : RaffleType.values()) {
            typeRa.addItem(topic.name());
        }

        this.emissionRa.addItem("Emisión");
        for (Raffle raffle : LotteryManager.getInstance().getRaffles()) {
            emissionRa.addItem(raffle.getEmission());
        }

    }

    private void refreshSearch() {

        String raffleName = (String) nameRa.getSelectedItem(); //Valida que hayan valores en el ComboBox.
        if (nameRa.getSelectedIndex() == 0) {
            raffleName = null;
        }

        String topicName = (String) typeRa.getSelectedItem();
        if (typeRa.getSelectedIndex() == 0) {
            topicName = null;
        }
        String emissionName = (String) emissionRa.getSelectedItem();
        if (emissionRa.getSelectedIndex() == 0) {
            emissionName = null;
        }

        Raffle newRaffle = new Raffle();
        newRaffle.setType(topicName);
        newRaffle.setEmission(emissionName);



        newRaffle.setName(raffleName);
        

        DefaultTableModel model = ((DefaultTableModel) raffleTable.getModel());
        model.setRowCount(0);
        for (Raffle raffle : LotteryManager.getInstance().searchRaffle(newRaffle)) {
            model.addRow(new Object[]{
                raffle.getName(), raffle.getEmission(), raffle.getType()
            });

        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        nameRa = new javax.swing.JComboBox<>();
        typeRa = new javax.swing.JComboBox<>();
        emissionRa = new javax.swing.JComboBox<>();
        pricesRa = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        raffleTable = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        raffleName = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Busqueda sorteos");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 20, -1, -1));

        nameRa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameRaActionPerformed(evt);
            }
        });
        getContentPane().add(nameRa, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        typeRa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                typeRaActionPerformed(evt);
            }
        });
        getContentPane().add(typeRa, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, -1, -1));

        emissionRa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emissionRaActionPerformed(evt);
            }
        });
        getContentPane().add(emissionRa, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 70, -1, -1));

        getContentPane().add(pricesRa, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 70, -1, -1));

        raffleTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nombre del sorteo", "Fecha del sorteo", "Tipo de sorteo"
            }
        ));
        jScrollPane1.setViewportView(raffleTable);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, 110));

        jButton1.setText("ver detalle del sorteo");
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 280, -1, -1));

        jButton2.setText("sorteos vistos");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, -1, -1));

        jButton3.setText("Atrás");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 240, 230, 100));
        getContentPane().add(raffleName, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 110, 150, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        Entrada usuario = new Entrada();
        usuario.setVisible(true);
        this.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Sorteosvistos usuario = new Sorteosvistos();
        usuario.setVisible(true);
        this.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void nameRaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameRaActionPerformed
        refreshSearch();        // TODO add your handling code here:
    }//GEN-LAST:event_nameRaActionPerformed

    private void typeRaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_typeRaActionPerformed
        refreshSearch();        // TODO add your handling code here:
    }//GEN-LAST:event_typeRaActionPerformed

    private void emissionRaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emissionRaActionPerformed
        refreshSearch();        // TODO add your handling code here:
    }//GEN-LAST:event_emissionRaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Busquedasorteos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Busquedasorteos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Busquedasorteos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Busquedasorteos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Busquedasorteos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> emissionRa;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JComboBox<String> nameRa;
    private javax.swing.JComboBox<String> pricesRa;
    private javax.swing.JTextField raffleName;
    private javax.swing.JTable raffleTable;
    private javax.swing.JComboBox<String> typeRa;
    // End of variables declaration//GEN-END:variables
}
