package GUI;

import Lottery.LotteryManager;
import Lottery.Tickets;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Fanny Brenes
 */
public class GestionTickets extends javax.swing.JFrame {

    private Tickets ticket;

    public Tickets getTickets() {
        return ticket;
    }

    /**
     * Creates new form GestionTickets
     */
    public GestionTickets() {
        initComponents();
        refreshTickets();
    }

    public void refreshTickets() {
        DefaultTableModel model = ((DefaultTableModel) ticketTable.getModel());
        model.setRowCount(0);
        
          for (Tickets ticket : LotteryManager.getInstance().getTickets()) {
            if (ticket.getRaffleType()=="Loteria"){
            model.addRow(new Object[]{
                ticket.getTransmitterName(), ticket.getRaffleType(), ticket.getNumber1(), ticket.getPrice()
            });}
            if (ticket.getRaffleType()=="Lotto"){
            String num1=Integer.toString(ticket.getNumber1());
            String num2=Integer.toString(ticket.getNumber2());
            String num3=Integer.toString(ticket.getNumber3());
            String num4=Integer.toString(ticket.getNumber4());
            String num5=Integer.toString(ticket.getNumber5());
            String num6=Integer.toString(ticket.getNumber6());
            String num7=Integer.toString(ticket.getNumber7());
            String combination=num1+","+num2+","+num3+","+num4+","+num5+","+num6+","+num7;
            String price=Integer.toString(ticket.getPrice());
            model.addRow(new Object[]{
                ticket.getTransmitterName(), ticket.getRaffleType(), combination, price
            });
        }
            if (ticket.getRaffleType()=="Bingo"){
            String num1=Integer.toString(ticket.getNumber1());
            String num2=Integer.toString(ticket.getNumber2());
            String num3=Integer.toString(ticket.getNumber3());
            String num4=Integer.toString(ticket.getNumber4());
            String num5=Integer.toString(ticket.getNumber5());
            String num6=Integer.toString(ticket.getNumber6());
            String num7=Integer.toString(ticket.getNumber7());
            String num8=Integer.toString(ticket.getNumber8());
            String num9=Integer.toString(ticket.getNumber9());
            String combination=num1+","+num2+","+num3+","+num4+","+num5+","+num6+","+num7+","+num8+","+num9;
            model.addRow(new Object[]{
                ticket.getTransmitterName(), ticket.getRaffleType(), combination, ticket.getPrice()
            });
        }
            if (ticket.getRaffleType()=="Tiempos"){
            String num1=Integer.toString(ticket.getNumber1());
            String num2=Integer.toString(ticket.getNumber2());
            String combination=num1+","+num2;
            model.addRow(new Object[]{
                ticket.getTransmitterName(), ticket.getRaffleType(), combination, ticket.getPrice()
            });
        }
      

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ticketTable = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        jButton3.setText("Modificar ticket");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Gestión de tiquetes");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, -1, -1));

        ticketTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nombre del emisor", "Tipo de sorteo", "Numero o combinación elegida", "Precio"
            }
        ));
        jScrollPane1.setViewportView(ticketTable);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 670, 140));

        jButton1.setText("Crear ticket");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 280, -1, -1));

        jButton2.setText("Eliminar ticket");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 280, -1, -1));

        jButton4.setText("Modificar ticket");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 280, -1, -1));

        jButton5.setText("Atrás");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        Gestionjps usuario = new Gestionjps();
        usuario.setVisible(true);
        this.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    TicketWindow usuario= new TicketWindow();
    usuario.setVisible(true);
    usuario.addWindowStateListener(new java.awt.event.WindowAdapter() {
        @Override
    public void windowDeactivated(java.awt.event.WindowEvent windowEvent){
    refreshTickets();
    }    
});        // TODO add your ha        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        LotteryManager.getInstance().removeTickets(this.ticketTable.getSelectedRow());
        refreshTickets();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestionTickets.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestionTickets.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestionTickets.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestionTickets.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GestionTickets().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable ticketTable;
    // End of variables declaration//GEN-END:variables
}
