package GUI;

import Lottery.Client;
import Lottery.LotteryManager;
import Lottery.Preorder;
import Lottery.Raffle;
import Lottery.Tickets;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Fanny Brenes
 */
public class Pedidocliente extends javax.swing.JFrame {

    DefaultTableModel tabla = new DefaultTableModel();
    

    private Preorder preorder;

    public Preorder getPreorder() {
        return preorder;
    }

    /**
     * Creates new form Pedidocliente
     */
    private void Updateraffle() {

        DefaultTableModel model = ((DefaultTableModel) Tablaticket.getModel());
        model.setRowCount(0);
        for (Tickets ticket : LotteryManager.getInstance().getTickets()) {

            if (ticket.getRaffleType() == "Loteria") {
                model.addRow(new Object[]{
                    ticket.getTransmitterName(), ticket.getRaffleType(), ticket.getNumber1(), ticket.getPrice()
                });
            }

            if (ticket.getRaffleType() == "Lotto") {
                String num1 = Integer.toString(ticket.getNumber1());
                String num2 = Integer.toString(ticket.getNumber2());
                String num3 = Integer.toString(ticket.getNumber3());
                String num4 = Integer.toString(ticket.getNumber4());
                String num5 = Integer.toString(ticket.getNumber5());
                String num6 = Integer.toString(ticket.getNumber6());
                String num7 = Integer.toString(ticket.getNumber7());
                String combination = num1 + "," + num2 + "," + num3 + "," + num4 + "," + num5 + "," + num6 + "," + num7;
                model.addRow(new Object[]{
                    ticket.getTransmitterName(), ticket.getRaffleType(), combination, ticket.getPrice()
                });
            }

            if (ticket.getRaffleType() == "Bingo") {
                String num1 = Integer.toString(ticket.getNumber1());
                String num2 = Integer.toString(ticket.getNumber2());
                String num3 = Integer.toString(ticket.getNumber3());
                String num4 = Integer.toString(ticket.getNumber4());
                String num5 = Integer.toString(ticket.getNumber5());
                String num6 = Integer.toString(ticket.getNumber6());
                String num7 = Integer.toString(ticket.getNumber7());
                String num8 = Integer.toString(ticket.getNumber8());
                String num9 = Integer.toString(ticket.getNumber9());
                String combination = num1 + "," + num2 + "," + num3 + "," + num4 + "," + num5 + "," + num6 + "," + num7 + "," + num8 + "," + num9;
                model.addRow(new Object[]{
                    ticket.getTransmitterName(), ticket.getRaffleType(), combination, ticket.getPrice()
                });
            }

            if (ticket.getRaffleType() == "Tiempos") {
                String num1 = Integer.toString(ticket.getNumber1());
                String num2 = Integer.toString(ticket.getNumber2());
                String combination = num1 + "," + num2;
                model.addRow(new Object[]{
                    ticket.getTransmitterName(), ticket.getRaffleType(), combination, ticket.getPrice()
                });
            }
        }
    }

    public Pedidocliente() {
        initComponents();
        Updateraffle();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tablaticket = new javax.swing.JTable();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Pedido de cliente");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 20, -1, -1));

        jButton1.setText("Consultar pedidos");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 360, -1, -1));

        jButton2.setText("Ordenar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 360, -1, -1));

        Tablaticket.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nombre del emisor", "Tipo de sorteo", "Numero o combinacion", "Precio"
            }
        ));
        jScrollPane1.setViewportView(Tablaticket);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 530, 210));

        jButton4.setText("Actualizar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Verificarcedula usuario = new Verificarcedula();
        usuario.setVisible(true);
        this.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        DefaultTableModel model = ((DefaultTableModel) Tablaticket.getModel());
        String emissorname = (String) Tablaticket.getValueAt(Tablaticket.getSelectedRow(), 0);
        String raffletype = (String) Tablaticket.getValueAt(Tablaticket.getSelectedRow(), 1);
        String number = Tablaticket.getValueAt(Tablaticket.getSelectedRow(), 2).toString();
        String pric = Tablaticket.getValueAt(Tablaticket.getSelectedRow(), 3).toString();
        int price = Integer.parseInt(pric);
        LotteryManager.getInstance().removeTickets(Tablaticket.getSelectedRow());
        Updateraffle();

        for (Client client : LotteryManager.getInstance().getClient()) {
            this.preorder = new Preorder();
            String name = client.getName();
            int age = client.getBirthdate();
            String correo=client.getEmail();
            this.preorder.setEmail(correo);
            this.preorder.setClientName(name);
            this.preorder.setNumber(number);
            this.preorder.setRaffleType(raffletype);
            this.preorder.setTransmittername(emissorname);
            this.preorder.setPrice(price);
            this.preorder.setAge(age);

            LotteryManager.getInstance().addpreOrder(preorder);
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        Updateraffle();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pedidocliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pedidocliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pedidocliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pedidocliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pedidocliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Tablaticket;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
